# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-19 12:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0004_delete_search'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=50)),
                ('contactno', models.ImageField(upload_to='')),
                ('query', models.TextField(max_length=2000)),
            ],
        ),
    ]
