# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-19 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0005_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contactno',
            field=models.IntegerField(),
        ),
    ]
